sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/serokell/log-warper/.stack-work"


matrix:
  include:

  - ghc: 8.0.2
    env: GHCVER='8.0.2' STACK_YAML="$HOME/build/serokell/log-warper/stack-$GHCVER.yaml"

  - ghc: 8.2.2
    env: GHCVER='8.2.2' STACK_YAML="$HOME/build/serokell/log-warper/stack.yaml"


addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc'
    packages:
      - libgmp-dev
      - cabal-install-2.0


before_install:

  - mkdir -p ~/.local/bin
  - export PATH="$HOME/.local/bin:$PATH"
  - travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version


install:

  - travis_wait 30 stack setup --no-terminal
  - stack ghc -- --version

  - travis_wait 40 stack build --only-dependencies --no-terminal
  - travis_wait 40 stack build --test --bench --no-run-tests --no-run-benchmarks --no-terminal


script:

  - travis_wait 40 stack build --test --no-terminal


notifications:
  email: false
  slack:
    rooms:
      - serokell:bZAMNe9sfjpyLFGIfYnlEmcy
    on_success: change
    on_failure: always
