# termSeveritiesOut : [Debug, Info, Notice] # severities which go to `stdout`
# termSeveritiesErr : Warning+              # severities which go to `stderr`

rotation:                                 # parameters for logger rotation
    maxSizeBytes: 256                     # size of file in bytes
    keepFiles: 3                          # max number of files to keep

global:                                   # global logging configuration
    showTid: true                         # show thread id
    logsDirectory: logs                   # directory for logs

tree:                                     # specify logger hierarchy
  severity: Warning+                      # severities for «root» logger
  node:                                   # logger named «node»
    severity: Debug+                      # severities for logger «node»
    file: skovoroda.log                   # messages for «node» will be sent to skovoroda.log
    comm:                                 # logger named «node.comm»
        severity: Info+                   # severities for logger «node.comm»
                                          # messages won't be printed to any file
